-
  - title: 客房服务
    icon: layout
    desc:
      是酒店无形和无价商品,随时随地的向客人出售。服务也可以说为满足他酒店服务人的需要而付出的智能和必要的劳动。
    color:
  - title: 餐饮服务
    icon: layout
    desc:
      是酒店无形和无价商品,随时随地的向客人出售。服务也可以说为满足他酒店服务人的需要而付出的智能和必要的劳动。
    color:
  - title: 旅游服务
    icon: layout
    desc:
      是酒店无形和无价商品,随时随地的向客人出售。服务也可以说为满足他酒店服务人的需要而付出的智能和必要的劳动。
    color:
-
  - title: 本市向导
    icon: layout
    desc:
      是酒店无形和无价商品,随时随地的向客人出售。服务也可以说为满足他酒店服务人的需要而付出的智能和必要的劳动。
    color: yellow
  - title: 机票服务
    icon: layout
    desc:
      是酒店无形和无价商品,随时随地的向客人出售。服务也可以说为满足他酒店服务人的需要而付出的智能和必要的劳动。
    color: yellow
  - title: 火车票服务
    icon: layout
    desc:
      是酒店无形和无价商品,随时随地的向客人出售。服务也可以说为满足他酒店服务人的需要而付出的智能和必要的劳动。
    color: yellow